### PR TITLE
Updated rubocop config file and fixed some violations.

### LINKED ISSUE #16: Rubocop configuration is out-of-date
```
$ bundle exec rubocop lib/bamboozled/api/employee.rb
bamboozled/.rubocop.yml: Lint/SpaceBeforeFirstArg has the wrong namespace - should be Style
Error: The `Style/TrailingComma` cop no longer exists. Please use `Style/TrailingCommaInLiteral` and/or `Style/TrailingCommaInArguments` instead.
(obsolete configuration found in bamboozled/.rubocop.yml, please update it)
```

From my Gemfile.lock
`rubocop (0.37.2)`

It looks like a number of the cops have been changed with the latest version of rubocop, while no version of rubocop is specified in the Gemfile. I updated the cops on my local box, and when it was finally running the existing project 32 offenses.

Depending on which direction the project want to take, I think the resolution here is to either 
- update the rubocop config to support the latest version of rubocop
- specify the rubocop gem version

### PR DESCRIPTION
**Pull request by Enriikke**
`require: rubocop-rspec` is causing an error in the latest rubocop release (0.38.0). I've disabled the require for now since it's causing Hound to fail. 

resolves #16

### CODE REVIEW

File: lib/bamboozled/api/time_off.rb [hunk 1]
```diff
@@ -14,7 +13,9 @@ def requests(options = {})
         # Make sure all statuses are allowed
         if options[:status]
           allowed_statuses = %w(approved denied superceded requested canceled)
-          options[:status] = Array(options[:status]).keep_if { |v| allowed_statuses.include? v }.join(",")
+          options[:status] = Array(options[:status])
+                             .keep_if { |v| allowed_statuses.include? v }
```
Comment (Enriikke) [inline lib/bamboozled/api/time_off.rb]: Hound is using the old rubocop config still. Once merged this will be valid style.

File: lib/bamboozled/api/time_off.rb [hunk 2]
```diff
@@ -14,7 +13,9 @@ def requests(options = {})
...
+                             .join(",")
```
Comment (Enriikke) [inline lib/bamboozled/api/time_off.rb]: Same as above.
